baseURL = "https://lingmacker-github-io.vercel.app/"
languageCode = 'zh-Hans'
title = "LM's Blog"
theme = "yinyang"

[params]
headTitle = "LM's Blog"
description = "Everyone is attached something."
favicon = "/favicon.png"

disqus = "lingmacker"
